apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-petclinic-app.fullname" . }}
  labels:
    {{- include "helm-petclinic-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-petclinic-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-petclinic-app.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-petclinic-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
#          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "NEW_RELIC_APP_NAME"
              valueFrom:
                secretKeyRef:
                  key: new_relic_app_name
                  name: {{ .Release.Name }}-auth
            - name: "NEW_RELIC_LICENSE_KEY"
              valueFrom:
                secretKeyRef:
                  key: new_relic_license_key
                  name: {{ .Release.Name }}-auth
            - name: "NEW_RELIC_HOST"
              valueFrom:
                secretKeyRef:
                  key: new_relic_host
                  name: {{ .Release.Name }}-auth
            - name: "NEW_RELIC_API_HOST"
              valueFrom:
                secretKeyRef:
                  key: new_relic_api_host
                  name: {{ .Release.Name }}-auth
            - name: "NEW_RELIC_METRIC_INGEST_URI"
              valueFrom:
                secretKeyRef:
                  key: new_relic_metric_ingest_uri
                  name: {{ .Release.Name }}-auth
            - name: "NEW_RELIC_EVENT_INGEST_URI"
              valueFrom:
                secretKeyRef:
                  key: new_relic_event_ingest_uri
                  name: {{ .Release.Name }}-auth
            - name: "NEW_RELIC_JFR_ENABLED"
              valueFrom:
                secretKeyRef:
                  key: new_relic_jfr_enabled
                  name: {{ .Release.Name }}-auth
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
