apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  new_relic_app_name: {{ .Values.new_relic_app_name | b64enc }}
  new_relic_license_key: {{ .Values.new_relic_license_key | b64enc }}
  new_relic_host: {{ .Values.new_relic_host | b64enc }}
  new_relic_api_host: {{ .Values.new_relic_api_host | b64enc }}
  new_relic_metric_ingest_uri: {{ .Values.new_relic_metric_ingest_uri | b64enc }}
  new_relic_event_ingest_uri: {{ .Values.new_relic_event_ingest_uri | b64enc }}
  new_relic_jfr_enabled: {{ .Values.new_relic_jfr_enabled | b64enc }}
