services:
  petclinic:
    image: new-relic-java-agent-docker-petclinic:petclinic-app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
